[Fix/YB-322] 팀 도메인 redis 적용 및 컨트롤러 부분 수정
Yellobook/yellobook-backend pull request #49
Opened 2024-08-11 15:28 UTC by SH-Seol

2024-08-12 02:24 UTC, Ywoosang requested changes

2024-08-12 02:24 UTC, Ywoosang commented on yellobook-api/src/main/java/com/yellobook/domains/team/service/TeamQueryService.java
> +    public List<MentionDTO> searchParticipants(TeamMemberVO teamMember, String name){
이 부분에서 리스트를 직접 반환하는 것보다, 별도 DTO 로 만들어서 반환하는게 더 좋을 것 같아요.

2024-08-12 02:24 UTC, Ywoosang commented on yellobook-api/src/main/java/com/yellobook/domains/team/controller/TeamController.java
> +            @RequestParam("name") String name,
파라미터 유효성 검증 추가해주세요 
만약에 값이 없는 경우에 기본 예외가 발생되는 것 보다 클라이언트에게 전달할 메시지를 설정해주는게 좋을 것 같아요.

2024-08-12 06:58 UTC, SH-Seol commented on yellobook-api/src/main/java/com/yellobook/domains/team/controller/TeamController.java
> +            @RequestParam("name") String name,
필요한 유효성 검증이 @로 시작하는지 확인하는 것과 값이 있는지 없는지가 맞을까요?

2024-08-12 12:55 UTC, jorippppong commented on yellobook-api/src/main/java/com/yellobook/domains/team/service/TeamQueryService.java
>          if(name.equalsIgnoreCase("@everyone")){
문자열 앞뒤에 공백이 포함될 수도 있어서 trim()을 사용해서 앞뒤 공백을 제거해주면 더 좋을 것 같아요!👍

2024-08-13 15:53 UTC, SH-Seol commented on yellobook-api/src/main/java/com/yellobook/domains/team/service/TeamQueryService.java
> +    public List<MentionDTO> searchParticipants(TeamMemberVO teamMember, String name){
MentionDTO 안에 List형태로 id를 담도록 수정했습니다!

2024-08-15 08:22 UTC, closed without merging