[Test/YB-229] 팀 도메인 Controller Unit Test 작성
Yellobook/yellobook-backend pull request #56
Opened 2024-08-18 14:08 UTC by SH-Seol

팀 도메인 컨트롤러에 대한 유닛 테스트를 작성하였습니다.

기존에는 리팩토링과 동시에 진행하고자 하였으나, 너무 많은 작업량의 PR은 가독성에도 좋지 않고

분리하여 올리는 것이 좀 더 명확하기에 테스트코드만 먼저 올립니다!

2024-08-18 15:47 UTC, jorippppong commented on yellobook-api/src/test/java/com/yellobook/domains/team/controller/TeamControllerTest.java
> +                        .principal(() -> customOAuth2User.getName())
해당 코드는 로그인한 사용자의 이름을 Principal 객체로 설정하는게 맞나요? 만약 맞다면 해당 부분이 어떤 역할을 하는지 궁금합니다!

2024-08-23 17:13 UTC, Ywoosang requested changes

2024-08-23 17:13 UTC, Ywoosang commented on yellobook-api/src/test/java/com/yellobook/domains/team/controller/TeamControllerTest.java
> +                teamId = 1L;
context 마다 동일한 값을 가지는 부분은 setUp 에서 초기화하지 않고 바로 초기화해도 될 것 같아요
```java
final Long teamId = 1;
```

2024-08-23 17:13 UTC, Ywoosang commented on yellobook-api/src/test/java/com/yellobook/domains/team/controller/TeamControllerTest.java
> +                code = "team:code";
"team:code" 는 redis 에 들어갈때 서버단에서 넣어주는 부분 아닌가요? 
프론트엔드에서 요청으로 전송된건 code 만 있으면 될 것 같아요!

2024-08-26 11:24 UTC, jorippppong approved these changes

2024-08-27 03:49 UTC, jorippppong approved these changes

2024-08-27 08:10 UTC, Ywoosang approved these changes

2024-08-27 10:19 UTC, merged