[Test/YB-230] 팀 도메인 Service Unit Test 추가
Yellobook/yellobook-backend pull request #60
Opened 2024-08-20 14:47 UTC by SH-Seol

## 📄 Work Description
<strong>Jira Ticket : `YB-230 `</strong>

#### 1. (작업 내용 간단 요약)
작업한 부분 설명 및 코드와 이미지 첨부
1. 팀 도메인의 Service의 유닛 테스트를 DCI의 형태에 맞춰 구현하였습니다.

2. 기존에 TeamCustomRepository에 작성된 findTeamMembers의 경우 실행하였을 때, 500에러가 발생하였습니다.
확인해본 결과
participant.team is not a root path 
org.springframework.dao.InvalidDataAccessApiUsageException: participant.team is not a root path
위와 같은 에러가 발생하였는데요.
따라서 해당 코드의 from(team)을 from(participant)로 변경하였습니다.

<br/>

## 💬 To Reviewers

DCI 패턴으로 테스트 코드를 작성하였는데, 아무래도 메소드 별 테스트 안에 BeforeEach를 넣으면 중복되는 부분이 너무 많다고 판단하여
밖으로 뺐습니다. 혹시 보시고 좀 더 깔끔한 형태로 변경할 수 있지 않을까 싶은 부분이 있으시면 편하게 말씀해주세요! 적극 반영하겠습니다.

<br/>

## 🔗 Reference
[//]: # (문제를 해결하면서 도움이 되었거나 참고했던 사이트 또는 코드 첨부)
https://www.inflearn.com/community/questions/879639/join-2%EB%B2%88-%EC%A7%88%EB%AC%B8%EC%9E%85%EB%8B%88%EB%8B%A4-is-not-a-root-path-%EC%97%90%EB%9F%AC

2024-08-20 20:28 UTC, Ywoosang requested changes

2024-08-20 20:28 UTC, Ywoosang commented on yellobook-domain/src/test/java/com/yellobook/domains/team/repository/TeamRepositoryTest.java
> +    @Test
DCI 적용하니까 확실히 깔끔해지고 가독성이 높아진 것 같네요 👍

이 부분도 DCI 반영해서

findAllTeamMembers 메소드는 
- 팀원이 존재할 경우 
    - 모든 팀원을 반환한다.
- 팀원이 존재하지 않을 경우
    - 빈 리스트를 반환한다.

처럼 바꾸면 좋을 것 같아요

2024-08-20 20:28 UTC, Ywoosang commented on yellobook-domain/src/main/java/com/yellobook/domains/team/repository/TeamCustomRepositoryImpl.java
> +                .join(participant.team, team)
이 부분이군요
방금 swagger 돌리면서 slack 에러로그 확인했습니다
고생하셨어요!!

2024-08-20 20:28 UTC, Ywoosang commented on yellobook-api/src/test/java/com/yellobook/domains/team/service/TeamCommandServiceTest.java
> +        class Context_Team_Member{
DCI 패턴의 흐름을 반영하려면 it 에서 given - when - then 을 모두 처리하는것보다 [링크](https://github.com/johngrib/example-junit5/blob/a5b4aeb4f7711dc84e3e531dc6f09815f392a949/src/test/java/com/johngrib/example/member/MemberRepositoryPassWithExtendsTest.java#L62) 처럼 구성하면 깔끔하게 만들 수 있을 것 같아요

2024-08-21 01:23 UTC, SH-Seol commented on yellobook-domain/src/test/java/com/yellobook/domains/team/repository/TeamRepositoryTest.java
> +    @Test
반영해서 새로 올리도록 하겠습니다!

2024-08-21 06:11 UTC, SH-Seol commented on yellobook-api/src/test/java/com/yellobook/domains/team/service/TeamCommandServiceTest.java
> +        class Context_Team_Member{
수정해서 push했는데 원하시는 방향? 이 맞는지 확인 부탁드립니다!

2024-08-21 08:38 UTC, jorippppong reviewed
Context가 특정 시나리오를 설정하고, It에서 결과를 검증하는 단계라서 Context에 시나리오 설정을 위한 값들을 추가하고, It에 그걸 검증하는 로직들을 배치하는게 좋을 것 같아요!

2024-08-21 08:39 UTC, jorippppong approved these changes, later dismissed

2024-08-23 11:55 UTC, Ywoosang approved these changes

2024-08-23 12:42 UTC, merged