[Test/YB-226] 공지 도메인 Repository Unit Test 작성
Yellobook/yellobook-backend pull request #66
Opened 2024-08-27 10:31 UTC by SH-Seol

[//]: # (PR 제목 예시 : [Feature/YB-1]: 소셜 로그인 기능 구현)

## 📄 Work Description
<strong>Jira Ticket : `YB-226 `</strong>

#### 1. (작업 내용 간단 요약)
작업한 부분 설명 및 코드와 이미지 첨부
Inform 도메인의 Repository Unit Test입니다.

<br/>

## 💬 To Reviewers

Inform과 관련된 3개의 리포지토리(공지, 댓글, 멘션)를 모두 분리하여 단위 테스트를 진행하였는데요.

이를 하나로 합치는 것이 더 좋을 것 같다고 생각하면 말씀 부탁드립니다!

그 외에 제가 놓친 것이나, 추가로 리뷰하실 것 있으시다면 리뷰해주시면 감사하겠습니다!

<br/>

## 🔗 Reference
[//]: # (문제를 해결하면서 도움이 되었거나 참고했던 사이트 또는 코드 첨부)

2024-08-30 06:47 UTC, Ywoosang requested changes

2024-08-30 06:47 UTC, Ywoosang commented on yellobook-domain/src/test/java/com/yellobook/domains/inform/InformMentionRepositoryTest.java
> +                em.merge(member2);
여기서 merge 를 사용하신 이유가 있을까요?

memberId 값은 jpa 가 관리하는 부분인데, 빌더에서 설정하지 못하도록 막는게 좋을 것 같네요 
@jorippppong  도 요거 의견 부탁드려요!

2024-08-30 06:47 UTC, Ywoosang commented on yellobook-domain/src/test/java/com/yellobook/domains/inform/InformMentionRepositoryTest.java
> +        member = MemberFixture.createMember();
Fixture 나 Utils 같은 것들은 static import 로 사용하는게 좋을 것 같아요

2024-08-30 06:47 UTC, Ywoosang commented on yellobook-domain/src/test/java/com/yellobook/domains/inform/InformRepositoryTest.java
> +    public InformRepositoryTest(InformRepository informRepository,
여기서 em 을 별도로 주입받아야 할까요?

2024-08-30 13:15 UTC, Ywoosang requested changes

2024-08-30 13:15 UTC, Ywoosang commented on yellobook-domain/src/test/java/com/yellobook/domains/inform/InformCommentRepositoryTest.java
> +    private Member member;
테스트의 독립성을 위해서 전역변수를 사용하지 않는 것이 좋아보여요

예를 들어, 한 테스트가 전역 변수의 상태를 변경하면, 다른 테스트에서 변경된 상태를 잘못 참조할 경우 예상치 못한 결과가 발생할 수 있습니다.

2024-08-31 07:10 UTC, SH-Seol commented on yellobook-domain/src/test/java/com/yellobook/domains/inform/InformCommentRepositoryTest.java
> +    private Member member;
음 그렇네요.. 맨 처음 구성할 때는 굳이 일일이 생성해야하나? 라고 해서 이렇게 했는데 제 생각이 좀 짧았던 것 같네요..

2024-08-31 07:29 UTC, SH-Seol commented on yellobook-domain/src/test/java/com/yellobook/domains/inform/InformMentionRepositoryTest.java
> +                em.merge(member2);
테스트를 코드를 작성할 때 의도했던 것은 memberId를 명시적으로 다르게 해서 구분된 멤버임을 보이고자 했는데,

그러다보니 detached상태로 관리가 되었고, 따라서 merge를 사용했었습니다.

근데 지나고 생각해보니 굳이 그럴 필요가 없었다고 생각을 하게 돼서 변경하도록 하겠습니다!

2024-08-31 07:29 UTC, SH-Seol commented on yellobook-domain/src/test/java/com/yellobook/domains/inform/InformRepositoryTest.java
> +    public InformRepositoryTest(InformRepository informRepository,
해당 부분은 삭제할게요!

2024-08-31 07:41 UTC, SH-Seol commented on yellobook-domain/src/test/java/com/yellobook/domains/inform/InformMentionRepositoryTest.java
> +        member = MemberFixture.createMember();
음.. 보는 입장에서나 작성하는 입장에서 그게 가독성, 편리성 면에서 좋겠군요..!

반영하겠습니다 ㅎㅎ

2024-08-31 21:56 UTC, Ywoosang commented on yellobook-domain/src/test/java/com/yellobook/domains/inform/InformCommentRepositoryTest.java
> +    private Member member;
저걸 전역으로 뺀다고 하면,
만약 BeforeEach 에서 누락해서 초기화를 안해줘도 다른 테스트에서 member 를 넣은 경우 잘못 실행될 수도 있습니다 

ex) 테스트1 에서 설정한 멤버가 테스트2에서도 이 변수로 접근 가능하기 때문

2024-09-01 10:05 UTC, SH-Seol commented on yellobook-domain/src/test/java/com/yellobook/domains/inform/InformCommentRepositoryTest.java
> +    private Member member;
위에 올리신 링크 봤습니다!

수정하겠습니다 ㅎㅎ

2024-09-10 06:27 UTC, Ywoosang approved these changes

2024-09-10 13:06 UTC, merged